const constants = {
    APISTATUS: 'APISTATUS',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    TOGGLE_NAV_DRAWER: 'TOGGLE_NAV_DRAWER',
    DASHBORD_COUNTERS: 'DASHBORD_COUNTERS',
    'CREATE_CENTER':'CREATE_CENTER',
    'DELETE_CENTER':'DELETE_CENTER',
    'LIST_CENTER':'LIST_CENTER',
    'UPDATE_CENTER':'UPDATE_CENTER',
    'CREATE_PARENT':'CREATE_PARENT',
    'DELETE_PARENT':'DELETE_PARENT',
    'LIST_PARENT':'LIST_PARENT',
    'UPDATE_PARENT':'UPDATE_PARENT',
}

export default constants